// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDImeQhx8e657WIQhvYWfprLBsdWQcEhx8',
    appId: '1:1091731018598:web:f82481b5f44c6eec2aaea7',
    messagingSenderId: '1091731018598',
    projectId: 'fish-specie-detector-app',
    authDomain: 'fish-specie-detector-app.firebaseapp.com',
    storageBucket: 'fish-specie-detector-app.appspot.com',
    measurementId: 'G-EVRQRWNRTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEPeu-plOjXVarN_IFjCNxPubvgMC8J4',
    appId: '1:1091731018598:android:139f0d0aa2d7296a2aaea7',
    messagingSenderId: '1091731018598',
    projectId: 'fish-specie-detector-app',
    storageBucket: 'fish-specie-detector-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8qByT5TpFwya2jnECNvO1f7263id06c',
    appId: '1:1091731018598:ios:aaee221bd5961afb2aaea7',
    messagingSenderId: '1091731018598',
    projectId: 'fish-specie-detector-app',
    storageBucket: 'fish-specie-detector-app.appspot.com',
    iosClientId: '1091731018598-ig73v1gfclsc6826vbvt159jhgi0jh4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishDetector',
  );
}
